services:
  - type: web
    name: stock-diios
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-diios-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: stock-diios-db
    databaseName: stock_diios
    user: stock_user
    plan: free
